### PR TITLE
link to htmlpreview for copyright

### PR DESCRIPTION
**Pull request by RedAuburn**
fixes https://github.com/organicmaps/organicmaps.github.io/issues/188

### CODE REVIEW

**Review by meenbeese — APPROVED** [review]

**Comment by biodranik** [comment]
I assume that .po files should be also updated using the script.

**Comment by RedAuburn** [comment]
regenerated 👍️

**Review by biodranik — APPROVED** [review]

**Comment by biodranik** [comment]
Did you forget to sign commits?

**Comment by biodranik** [comment]
@RedAuburn is that email bound to the github?

@rtsisyk why it says that commits should be signed?

выява

**Comment by RedAuburn** [comment]
> @RedAuburn is that email bound to the github?

it should have been.  I've changed my commit email to my proper email now, is it working?

**Comment by rtsisyk** [comment]
> > @RedAuburn is that email bound to the github?
> 
> it should have been. I've changed my commit email to my proper email now, is it working?

"Require signed commits" (=GPG signing) checkbox was enabled for some reason... I have fixed that.

**Pull request merged**
