### PR TITLE
Correct weekly -> weeklong

### PR DESCRIPTION
**Pull request by black-puppydog**
I think the meaning was supposed to be that the trip lasts a week, not that we do one trip every week. :)

Very cool project by the way, found out about it last week and have been loving it!

### CODE REVIEW

**Review by biodranik — APPROVED** [review]
Thanks, indeed! 😄 

@rtsisyk PTAL

**Comment by black-puppydog** [comment]
@rtsisyk you mean me?

Sorry for the confusion, I did read the comment in the "Checks" tab, but don't understand what's exactly expected of me... Am I the one signing off? Or did you? I mean, sure I can use `--sign-off` but what difference does it make whether a total stranger on the interwebs signs off on their own commit? :D

**Comment by biodranik** [comment]
@black-puppydog contributors (including ourselves) sign their commits with the real contributor's name and email.

**Comment by black-puppydog** [comment]
Okay, done. I rebased and dropped your merge commit in the process, hope that was okay.
I also changed the extra three translations that were added in the meantime.

**Review by biodranik — APPROVED** [review]
Thank you!

**Pull request merged**
