### PR TITLE
Add trackercontrol link

### PR DESCRIPTION
**Pull request by Jean-BaptisteC**
Fixed https://github.com/organicmaps/organicmaps/issues/5173

First contribution on website generated by Zola
I'm on windows, i don't know how to generate .po file, i can't use po4a

### CODE REVIEW

**Comment by biodranik** [comment]
@Jean-BaptisteC there is a relevant discussion here: https://github.com/mquinson/po4a/issues/370

I think you can build it on Windows if you install Perl.

Another option is to install WSL2 and use it from there.

**Comment by Jean-BaptisteC** [comment]
I have make Github Actions to regenerate translations but script sh have doing a lot of changes and in somes cases replace real translations by english translations in PO and md files.
To regenerate, i just have need to update index.md and content.pot ?

**Comment by biodranik** [comment]
@rtsisyk can you please help?

It's better to do it locally.

**Comment by Jean-BaptisteC** [comment]
@biodranik PTAL
I have update manually PO files

**Comment by biodranik** [comment]
@rtsisyk can you please double-check that this PR doesn't break translations, and finish it if necessary?

**Comment by rtsisyk** [comment]
All good, no issues with translations. Merged. Thanks!

**Pull request merged**
