### PR TITLE
User Support Champion Wanted

### PR DESCRIPTION
**Pull request by rtsisyk**
Are you interested in being part of tech support in a global community that is changing the way we think about navigation and privacy? As a Community Support Champion you will be working directly with people in the community who use Organic Maps, to provide technical support and assistance with the application and website. The community ranges from tech savvy engineers, to novice technology users. Support involves maintaining customer satisfaction, resolving technical challenges, and enhancing the support experience, to ensure people have a better overall navigation experience.

Your expertise and dedication will be rewarded. If you are passionate about improving the user experience and supporting our community-driven project, we'd love to hear from you. Contact us at team@organicmaps.app, and let's discuss how you can make an impact!

## 

The text was written by @oleg-rswll in October 2023 but was never published.

### CODE REVIEW

**Review by oleg-rswll — APPROVED** [review]

**Comment by oleg-rswll** [comment]
For the title, how about "Community Support Engineer"?

**Comment by pastk** [comment]
I like it more than "User support" :heart:

**Comment by rtsisyk** [comment]
> For the job title, how about "Community Support Engineer"?

What is about the current "Community Engagement Specialist"?

**Comment by oleg-rswll** [comment]
> > For the job title, how about "Community Support Engineer"?
> 
> What is about the current "Community Engagement Specialist"?

"Engagement" is usually related to partnerships, but that could work.

The title is made of three parts, each word describing different things:

1) Noun of who the service is for
Words: Community, User

2) Verb about what the role does
Words: Support, Care, Engagement, Operations

3) Noun about who the person is doing the job
Words: Specialist, technician, analyst

**Comment by pastk** [comment]
> What is about the current "Community Engagement Specialist"?

This is someone from the Growth team :)

**Pull request merged**
