### PR TITLE
Improved Ukrainian translation

### PR DESCRIPTION
**Pull request by strump**
- Fixed errors.
- Finished translation of english sentences.

### CODE REVIEW

**Review by biodranik — COMMENTED** [review]
Are these strings translated using Weblate? Then they should be updated in the .po files too.

**Comment by strump** [comment]
@biodranik I didn't change `.po` files. Will update

**Comment by strump** [comment]
@biodranik Copied changes to `content.uk.po` file.

**Review by biodranik — APPROVED** [review]
Дякую!

**Pull request merged**
