### PR TITLE
Prettify md/scss and update dependencies

### PR DESCRIPTION
**Pull request by meenbeese**
I ran `npm i && npm run format` and `npm run upgrade` to fix linting and update a few deps.

### CODE REVIEW

**Comment by biodranik** [comment]
@rtsisyk did it break po4a?

@meenbeese did you test po4a localization tool? What caused so many format changes? Is it possible to avoid replacement somehow?

**Comment by meenbeese** [comment]
> did you test po4a localization tool? What caused so many format changes? Is it possible to avoid replacement somehow?

No, how can I test that? I just did the prettify as suggested.
I don't see why we should try to avoid the replacements.

**Review by biodranik — COMMENTED** [review]
`npm run format` does not produce these changes on my Mac. Can you please take the latest version from the master branch and try to understand why it happens? Do you have a different global config for the formatter?

**Comment by meenbeese** [comment]
I tried with the latest version from master but it still produces the same result. And I didn't set up any different config for the formatter either, just using the default one.

As this is not especially important, I can just close the PR and focus on more important issues that need to be resolved. The only formatting critical for me is this in the main.css:

```
@media (width <= 768) {
```

As zola serve refuses to compile for me when it is as such. I have to change it to:

```
@media (max-width: 768) {
```

Which I had previously did in my last merged PR but it was reverted when you ran your formatter. How can we solve this?

**Comment by biodranik** [comment]
1. Please avoid merge commits and always use rebase. You may need to practice a bit to better understand it. It is required in our git workflows.
2. I don't have any build issues with zola related to scss. What is your zola version? Could it be that you have some conflicting global npm packages installed that influence the behavior of the formatter and scss transpiler?

**Comment by meenbeese** [comment]
> 1. Please avoid merge commits and always use rebase. You may need to practice a bit to better understand it. It is required in our git workflows.

Thanks, I will try to explore rebase a bit more.

> 2. I don't have any build issues with zola related to scss. What is your zola version?

My zola version is 0.16.1

> Could it be that you have some conflicting global npm packages installed that influence the behavior of the formatter and scss transpiler?

I do have Prettier installed which may be the culprit behind the formatting changes but that doesn't explain the scss compiling error.

**Comment by biodranik** [comment]
```
✗ zola --version
zola 0.17.2
```
Please install the latest zola version.

**Comment by meenbeese** [comment]
I can confirm that updating the zola version to 0.17.2 solved the error completely. Maybe we should document this in the README? I was planning on improving the README anyway sometime.

**Comment by biodranik** [comment]
You can clarify there that we're using the latest zola.

**Pull request closed without merging**
