### PR TITLE
Clear the style of visited links

### PR DESCRIPTION
**Pull request by ZOPtTMX22zcBAl6i1HbGPbFwZzuelxkr8Zlq1t3**
Update main.scss

### CODE REVIEW

**Comment by biodranik** [comment]
Why do you think that not seeing visited links is better? It makes it easier for users to read news, or check some site sections.

**Comment by ZOPtTMX22zcBAl6i1HbGPbFwZzuelxkr8Zlq1t3** [comment]
> Why do you think that not seeing visited links is better? It makes it easier for users to read news, or check some site sections.

On some devices, it cannot be seen as a link.

**Comment by biodranik** [comment]
> On some devices, it may be confused with regular text.

Are you speaking about the menu links or the links in the text? Some examples may make it more clear. All links, either visited or unvisited, are now underlined. It's hard to be confused. The only exception is the top/bottom menu, but it may need a different styling instead.

**Comment by rtsisyk** [comment]
Closing as stale. Please feel free to re-open.

**Pull request closed without merging**
