### PR TITLE
Updated news for the latest release

### PR DESCRIPTION
**Pull request by biodranik**

### CODE REVIEW

**Comment by biodranik** [comment]
@organicmaps/translations can you please help to translate news into your language? Just post a comment here with the translation.

**Comment by LaoshuBaby** [comment]
```
---
title: '此版本已含HOTOSM团队在土耳其和叙利亚地震后所做的更改'
date: 2023-02-14T23:23:55+00:00
slug: "this-release-includes-the-updated-map-data-for-turkey-and-syria-including-the-humanitarian-openstreetmap-team-changes-after-the-recent-earthquake"
---

此版本包括更新的土耳其和叙利亚地图数据，包括[人道主义 OpenStreetMap 团队](https://www.hotosm.org/)在地震后做出的贡献。准确的地图对于灾难后的应急响应至关重要，因为它们可以更好地为当地的救援人员提供路线指引。我们感谢所有为 OpenStreetMap 做出过贡献的人。若您也想参与贡献，可点击[此处](https://www.openstreetmap.org/user/Heather%20Leson/diary/400951)。

Organic Maps在版本中做出的更改列表：
* 截止2月10日的OpenStreetMap数据
* 在列表和地图上过滤不正确的搜索结果
* 改进了小距离的下一转弯通知
* 主楼和陪楼更好的入口图标
* 修复了波兰语和德语的翻译，改进了波斯语显示。

Android
* 修复了启动时崩溃的问题
* 修复了编辑器中不可见的错误消息

iOS
* 修复了打开 om:// 和 <https://omaps.app/> 链接时的崩溃问题 
* 在 om:// 和 <https://omaps.app/> 链接中显示共享 POI 的名称

查看更多适用于 Android 和 iOS 的 API 和 URL 模式示例，请访问 <https://omaps.app/api>

```

I am more curious why commit is not allowed to complete the submission, because I think it is also very important to keep the translator's commit record.

**Comment by nautilusx** [comment]
@biodranik Please provide all other components (news, app strings,...) on weblate. It's easier for all and we can increase the quality. You can automagically merge the translations and the translators have an easier way to translate.

**Comment by Wivik** [comment]
French version :

```
Cette version comprend les cartes mises à jour pour la Turquie et la Syrie, incluant les changements de l'[Humanitarian OpenStreetMap Team](https://www.hotosm.org/) après le récent tremblement de terre. Des cartes précises sont cruciales pour répondre aux catastrophes car elles peuvent fournir une aide pour préparer et guider l'aide sur place. Nous remercions toutes les personnes ayant contribué à OpenStreetMap. Vous pouvez contribuer dès à présent en suivant le [lien suivant](https://www.openstreetmap.org/user/Heather%20Leson/diary/400951).

Liste des changements dans cette version d'Organic Maps :

Nouvelles données OpenStreetMap au 10 février
Filtrage des résultats incorrects à la fois dans la liste et sur la carte
Amélioration des notifications de virage suivant pour les courtes distances
Meilleures icônes pour les entrées principales et secondaires d'immeubles
Amélioration de la langue persan et correction d'erreurs dans la traduction polonaise et allemande

Android

- Correction d'un plantage au lancement
- Correction d'un message d'erreur invisible dans l'Editeur

iOS

- Correction d'un plantage lors de l'ouverture des liens om:// et https://omaps.app/
- Affichage du nom du Point d'Intérêt dans les liens om:// et https://omaps.app/

Retrouvez plus d'exemples d'utilisation de notre API et schéma d'URL pour Android et iOS sur https://omaps.app/api
```

**Comment by biodranik** [comment]
> I am more curious why commit is not allowed to complete the submission, because I think it is also very important to keep the translator's commit record.

We need to merge it to publish the English translation ASAP. Weblate would be a better option, but it requires some work to support news translations properly. You of course can create a separate pull request if it's important to you!

**Comment by jimcarst** [comment]
nl
```
Deze versie bevat geüpdatete kaartengegevens voor Turkije en Syrië, inclusief de [Humanitarian OpenStreetMap Team](https://www.hotosm.org/) aanpassingen na de recente aardbeving. Nauwkeurige kaarten zijn cruciaal in ramp-respons, omdat ze helpen bij betere planning en navigatie voor helpers in het veld. We zijn iedereen die ooit heeft bijgedraagd aan OpenStreetMap dankbaar. Als je nu wil beginnen met bijdragen, volg dan [deze link](https://www.openstreetmap.org/user/Heather%20Leson/diary/400951).

De lijst met veranderingen in deze Organic Maps versie:

Nieuwe OpenStreetMap data sinds 10 februari
Filter foute zoekresultaten in de lijst en op de kaart
Verbeterde volgende stop-meldingen voor korte afstanden
Betere iconen voor hoofd- en zij-ingangen
Betere Perzische vertalingen en opgeloste fouten in de Poolse en Duitse vertalingen

Android
Opgelost: crash bij openen
Opgelost: onzichtbare errormeldingen in de bewerkingsmodus

iOS
Opgelost: crash bij het openen van om:// en https://omaps.app/ links
We laten nu de gedeelde POI naam zien in om:// en https://omaps.app/ links
Kijk voor meer voorbeelden van onze API en URL schema's voor Android en voor iOS ophttps://omaps.app/api
```

**Pull request merged**
