### PR TITLE
Minor rewording and grammar fixes

### PR DESCRIPTION
**Pull request by meenbeese**
This PR spun off from #169 to:
- Correct some minor grammar mistakes
- Update the click wording to be more personal
- Update the GH issue count to the current one

To preview the changes: https://a0bf1bbd.organicmaps-github-io.pages.dev/
So I was able to get a preview right from this PR, how did that work?

### CODE REVIEW

**Review by biodranik — APPROVED** [review]
Thank you!

**Comment by biodranik** [comment]
We can provide a write access to the repo for active contributors, so it would be easier to preview deployments automatically.

**Comment by meenbeese** [comment]
> We can provide a write access to the repo for active contributors, so it would be easier to preview deployments automatically.

Yes, I would appreciate that as it would be much easier to actually focus on the changes instead of dealing with preview links :/

**Comment by biodranik** [comment]
@meenbeese after accepting invitation you can push branches to the main repo and easily test deployments )

**Pull request merged**
