### PR TITLE
[style] Make dark mode background a bit lighter

### PR DESCRIPTION
**Pull request by Mr-Mime**
Right now the background is pure black.

This change makes it to a light grey and thereby reduces the contrast.
This helps when reading.

It is good, as the text color already is a "darker" white.

Just thought I'll create the PR let me know what you think

Current production:
prod

With new background:
dark

### CODE REVIEW

**Comment by biodranik** [comment]
I'm not sure that greyish background is better. Contrast may be tuned by reducing the font brightness, instead of increasing the background brightness, which makes more stress to (at least my) eyes. What do you think?

**Comment by Mr-Mime** [comment]
I agree that it might be something I prefer personally but others don't.

However I just realized that all other web sites I am surfing are using some type of grey instead of pure black.

Stated [here](https://css-tricks.com/a-complete-guide-to-dark-mode-on-the-web/#aa-dark-mode-colors) is that it improves readability.

Also [here](https://css-tricks.com/a-complete-guide-to-dark-mode-on-the-web/#aa-dark-mode-in-the-wild) are some other examples.

**Comment by biodranik** [comment]
In the article, they compare pure black bg with pure white text. What about reducing the text brightness a bit?

I personally prefer pure black, it is less painful for the eyes in the dark. But I'm ok to try the same color as GitHub is using.

Can you please sign your commit to pass DCO check?

**Comment by Mr-Mime** [comment]
Fixed the DCO.

However I do not want to force you to accept this new color.
Else next week some one creates a  PR saying "I prefer the background color to be XY" and so on :D

Hope you understand what you mean.


An idea would be to allow the user to choose a "pure black"  or "light dimm" theme.
However I think this would be more work than it outputs...

**Review by biodranik — APPROVED** [review]
Let's check how it works.

**Pull request merged**
