### PR TITLE
[news] Minor fixes for Turkish translation

### PR DESCRIPTION
**Pull request by MetehanOzyurek**
It doesn't show articles properly

Typos in the #118 fixed

### CODE REVIEW

**Comment by MetehanOzyurek** [comment]
## Before:
resim
## After:
resim

**Review by biodranik — COMMENTED** [review]
Didn't I fix it already?

**Comment by MetehanOzyurek** [comment]
> Didn't I fix it already in https://github.com/organicmaps/organicmaps.github.io/commit/213d667a801821288ecd5a1df4ed844bc813fc7b?

Yes, I created this PR before you fix. So don't need to merge.

**Comment by biodranik** [comment]
Sorry, I didn't see your PR :( But it's great that we fixed it!

**Pull request closed without merging**
