### PR TITLE
New site

### PR DESCRIPTION
**Pull request by maltejur**
Hey everyone,

I made a improved version of the website with the same content as the old one. You can take a look here:

https://organicmaps.vercel.app/

What do you think about it?

### CODE REVIEW

**Comment by biodranik** [comment]
Hi! The most important question: why parcel/vercel?

**Comment by maltejur** [comment]
I used parcel because a full ssg seemed a bit overkill so I used parcel as the bundler with a bit of posthtml.

Vercel ist just to show you how the site will look. You can still use Github Pages or Cloudflare Pages.

**Comment by biodranik** [comment]
We have a good experience with Hugo, and zola is almost the same by core features (but simpler). And we want to have an easy option to add multilingual content in the future, so the parcel does not fit well here.

Regarding the design, scrolling screenshots may be a good option for mobile devices in portrait mode, but for landscape screens it's better to show more useful information without waiting. Also, the device's size in your layout could be better, screenshots look very small on my iPhone.

**Comment by maltejur** [comment]
Okay then

**Comment by victorbnl** [comment]
As you can see above I ported this site to Zola : #15

**Pull request closed without merging**
