### PR TITLE
Style improvements

### PR DESCRIPTION
**Pull request by dustdfg**
Signed-off-by: DustDFG <dfgdust@gmail.com>

### CODE REVIEW

**Comment by biodranik** [comment]
Thanks! Can you please sign the commit (or PR's description, if you can't amend by any reason)? You need to add this line to commit's description:
```
Signed-off-by: Your Name <your@email>
```

**Comment by dustdfg** [comment]
@biodranik  It seems to me that I did it. Is it enough?

**Comment by biodranik** [comment]
Aha, I see, only one commit is authored with DCO. All of them should be signed (or you/we can squash them).

**Comment by dustdfg** [comment]
@biodranik I am a new user on GitHub and I don't understand what is DCO.

**Comment by biodranik** [comment]
> @biodranik I am a new user on GitHub and I don't understand what is DCO. How do I correct it without command-line?

We use DCO to author commits because of legal issues. The only way to fix it without a command line is to add DCO line in the PR, so we can squash it during the merge.

**Review by biodranik — APPROVED** [review]
Thanks for the contribution!

**Pull request merged**
