### PR TITLE
Enable Italian

### PR DESCRIPTION
**Pull request by rtsisyk**
Signed-off-by: Roman Tsisyk <roman@tsisyk.com>

### CODE REVIEW

**Comment by rtsisyk** [comment]
@organicmaps/translations-it @Genio2003, please review/edit.

**Comment by FinixFighter** [comment]
> back = "Torna alle Notizie" contact = "Contattaci" donate = "Dona" home = "Pagina Iniziale" news = "Notizie" support-us = "Contribuisci"
> 
> I think these translations suit the words better.

back = "Torna alle Notizie" is ok if you mean "Back to news". If you just mean "back", then "Indietro" would be better.

**Review by biodranik — CHANGES_REQUESTED** [review]
@rtsisyk please check the preview URL https://887b69a4.organicmaps.pages.dev/it/ : you need to use double quotes in some places.

**Comment by rtsisyk** [comment]
I have fixed all formatting errors. Please take a look.

**Comment by rtsisyk** [comment]
https://rt-italian.organicmaps.pages.dev/

**Review by Genio2003 — APPROVED** [review]

**Pull request merged**
